### PR TITLE
Allow html to be converted to richtext

### PR DESCRIPTION
**Pull request by shemgp**
Thanks for the great work for this library.  I needed to be able to convert html code inside the `<td></td>` to rich text for each spreadsheet cell.  Here's the PR that will enable that.  I used the builtin `toRichTextObject` of PHPSpreadsheet to convert html code to richText.

Thanks for considering this.

### CODE REVIEW

**Comment by sprain** [comment]
Could you provide an example of with what html table you would use this?

**Comment by shemgp** [comment]
Here's the sample html table.  I'm wanting the Questions column to retain the font style (strong).
[richtext.html.txt](https://github.com/Ticketpark/HtmlPhpExcel/files/3366357/richtext.html.txt)

**Comment by sprain** [comment]
Unfortunately, your code changes break other features:

* Formulas do not get executed anymore
* Number formats don't work anymore
* Setting explicit cell data type does not work anymore

You can compare the generated test file of master and of your pr by running `php example/example.php` within this repository.

**Comment by sprain** [comment]
I will close this now as there seems to be no demand.

**Pull request closed without merging**
