### PR TITLE
fix cell merging functionalities

### PR DESCRIPTION
**Pull request by fengyungithub**
cell merging functionalities, support merge cell with "colspan" and "rowspan"

### CODE REVIEW

**Comment by sprain** [comment]
It's already there. See this line in the example: https://github.com/Ticketpark/HtmlPhpExcel/blob/892666993fa1be3b2df560be424f13bf4565fa9b/example/example.html#L58

I just ran this example file and it worked.

**Comment by sprain** [comment]
Sorry, my bad.
I misread your comment as an issue, not as a pull request. Too early in the morning yet :)

Could you please provide an example of what exactly your code fixes?

**Comment by fengyungithub** [comment]
<table>
    <tr>
        <td rowspan="2" colspan="2">项目</td>
        <td colspan="2">上期</td>
        <td colspan="1">本期预算</td>
        <td colspan="2">增长情况</td>
    </tr>
    <tr>
        <td>上期预算</td>
        <td>上期实际</td>
        <td>合计</td>
        <td>较上期预算增长</td>
        <td>较上期实际增长</td>
    </tr>
</table>

like this table,  the old logic will `went` wrong.

**Comment by fengyungithub** [comment]
when the column with "colspan" or "rowspan" not  the last cell of row,  the merge cell will going wrong.

**Comment by sprain** [comment]
I see.
Looks good to me and seems to make sense.

**Pull request merged**
